### ISSUE TITLE
samples.nancyfx.org is not working

### ISSUE THREAD

**Issue by petriashev** [NancyFx/Nancy.Demo.Samples#6]
samples.nancyfx.org is not working.
Only empty home page

**Comment by thecodejunkie** [comment]
Yeah we were hosting the database at MongoHQ and they closed down their hosting service.. need to figure out an alternative

**Comment by 1kastner** [comment]
any solution in sight?

**Comment by thecodejunkie** [comment]
Sorry not really looked into this as we only had a handful of small samples.. most of them are on my GitHub account
